[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "synexify"
version = "0.1.0"
description = "Synexify - Django DDD Application"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

dependencies = [
    "Django>=6.0rc1",
    "djangorestframework>=3.15",
    "djangorestframework-simplejwt",
    "python-dotenv>=1.0",
    "psycopg2-binary>=2.9",
]

[project.optional-dependencies]
# dependencies for development
dev = [
    "ruff==0.2.1",
    "black==24.2.0",
    "mypy==1.8.0",
    "django-stubs==4.2.7",
    "pre-commit==3.6.0",
]

# depenciencies for tests
test = [
    "pytest==7.4.4",
    "pytest-django==4.7.0",
    "pytest-cov==4.1.0",
    "factory-boy==3.3.0",
    "faker==22.0.0",
    "model-bakery"
]

# dependencies for local development
all = [
    "synexify[dev,test]",
]

[project.urls]
Homepage = "https://github.com/Boguszera/Synexify"
Repository = "https://github.com/Boguszera/Synexify"
Issues = "https://github.com/Boguszera/Synexify/issues"

# ============================================================================
# build configuration (setuptools discovery) - docker fix
# ============================================================================
[tool.setuptools.packages.find]
include = [
    "appcore",
    "application",
    "domain",
    "infrastructure"
]
exclude = [
    "media*",
    "staticfiles*",
    "tests*"
]

# ============================================================================
# tools configuration
# ============================================================================

[tool.ruff]
target-version = "py312"
line-length = 120

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "*/migrations/*",
    "staticfiles",
    "media",
]

src = ["appcore", "application", "domain", "infrastructure", "tests"]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes (logical errors)
    "I",   # isort (sort imports alphabetical)
    "C90", # mccabe (cyclomatic complexity)
    "N",   # pep8-naming (nomenclature: snake_case, CamelCase)
    "D",   # pydocstyle (docstrings)
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "DJ",  # flake8-django
    "S",   # flake8-bandit (security issues)
    "PT",  # flake8-pytest-style
]

ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D106", # Missing docstring in public nested class
    "D107", # Missing docstring in __init__
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "N818", # exceptions names
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D", "S101", "S106"]  # Docstrings and asserts (security) in tests
"*/settings.py" = ["S105", "S106"]  # secret keys (.env)
"manage.py" = ["D"] # docstrings in manage.py (autogenerated)
"**/migrations/*" = ["ALL"]  # ignore migrations
"infrastructure/orm/management/commands/seed.py" = ["ALL"]
"__init__.py" = ["F401"]
"*/models.py" = ["F401"]
"*/models/*.py" = ["F401"]

[tool.ruff.lint.mccabe]
max-complexity = 11 # cyclomatic complexity

[tool.ruff.lint.isort]
known-first-party = ["appcore", "application", "domain", "infrastructure"]

[tool.black]
line-length = 120
target-version = ['py312']
exclude = '''
/(
    \.git
  | \.venv
  | \.tox
  | migrations
  | staticfiles
  | media
)/
'''

[tool.mypy]
python_version = "3.12"
plugins = ["mypy_django_plugin.main"]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
exclude = [
    "migrations/",
    "tests/",
]

[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "appcore.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "appcore.settings"
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--verbose",
    "--strict-markers",
    "--cov=appcore",
    "--cov=application",
    "--cov=domain",
    "--cov=infrastructure",
    "--cov-report=html",
    "--cov-report=term-missing",
]
testpaths = ["tests"]

[tool.coverage.run]
source = ["appcore", "application", "domain", "infrastructure"]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/__pycache__/*",
    "*/venv/*",
    "manage.py",
]

[tool.coverage.report]
precision = 2
show_missing = true
skip_covered = false
