# Generated by Django 6.0.2 on 2026-02-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmodel",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                default="low",
                max_length=20,
            ),
        ),
    ]
